# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-27 20:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messages', '0002_auto_20180608_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='html_formatted',
            field=models.BooleanField(default=False),
        ),
    ]
