# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-13 14:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0016_merge_20181113_1453'),
        ('videos', '0012_auto_20180830_1256'),
        ('amara_auth', '0008_auto_20180904_1910'),
        ('activity', '0009_auto_20180919_0026'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='activityrecord',
            index_together=set([('user', 'copied_from', 'created'), ('team', 'type', 'created'), ('team', 'type', 'video_language_code', 'created'), ('team', 'user', 'created'), ('team', 'language_code', 'created'), ('video', 'copied_from', 'created'), ('team', 'created')]),
        ),
    ]
