# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-26 15:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0010_auto_20181113_1458'),
        ('activity', '0010_auto_20181116_1554'),
    ]

    operations = [
    ]
