# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-25 17:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0010_team_tags'),
        ('teams', '0011_auto_20180919_0026'),
    ]

    operations = [
    ]
