# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-10 09:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0012_merge_20180925_1711'),
        ('teams', '0012_auto_20180919_0027'),
    ]

    operations = [
    ]
