# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-17 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0013_merge_20181010_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='membership_policy',
            field=models.IntegerField(choices=[(4, 'Open'), (1, 'Application'), (3, 'Invitation by any team member'), (2, 'Invitation by manager'), (5, 'Invitation by admin')], default=5, verbose_name='membership policy'),
        ),
        migrations.AlterField(
            model_name='team',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='teams', to='teams.TeamTag'),
        ),
    ]
