# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-13 14:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0015_auto_20181024_1425'),
        ('teams', '0015_auto_20181015_1329'),
    ]

    operations = [
    ]
