# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-09 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subtitles', '0006_auto_20180919_0026'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtitlelanguage',
            name='soft_limit_cpl',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='subtitlelanguage',
            name='soft_limit_cps',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='subtitlelanguage',
            name='soft_limit_lines',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='subtitlelanguage',
            name='soft_limit_timing',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
