# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-12 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subtitles', '0007_auto_20181009_1522'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subtitlelanguage',
            old_name='soft_limit_timing',
            new_name='soft_limit_min_duration',
        ),
        migrations.AddField(
            model_name='subtitlelanguage',
            name='soft_limit_max_duration',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
