# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-29 06:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('externalsites', '0003_youtubeaccount_sync_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='synchistory',
            name='is_latest',
            field=models.BooleanField(default=False),
        ),
    ]
