# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-29 06:27
from __future__ import unicode_literals

from django.db import migrations

# since we moved teams.Team.sync_metadata attribute to externalsites.YouTubeAccount.sync_metadata
# we update the existing linked youtube accounts to teams to reflect the correct value
def update_team_youtube_accounts(apps, schema_editor):
    Team = apps.get_model('teams', 'Team')
    YouTubeAccount = apps.get_model('externalsites', 'YouTubeAccount')

    for team in Team.objects.all():
        YouTubeAccount.objects.filter(
            type='T',
            owner_id=team.id).update(sync_metadata=team.sync_metadata)

# set the is_latest field to True for SyncHistory objects that are
# the latest per video_url - language combination
def update_sync_history_is_latest(apps, scheme_editor):
    SyncHistory = apps.get_model('externalsites', 'SyncHistory')

    # SyncHistory.objects.values('video_url', 'language').annotate(datetime=Max('datetime')).update(is_latest=True)
    flagged = {}
    for sh in SyncHistory.objects.all().order_by('-datetime'):
        if (sh.video_url.pk, sh.language.language_code) in flagged:
            continue
        sh.is_latest = True
        sh.save()
        flagged[(sh.video_url.pk, sh.language.language_code)] = 1

class Migration(migrations.Migration):

    dependencies = [
        ('externalsites', '0004_synchistory_is_latest'),
        ('teams', '0016_auto_20181116_1554'),
    ]

    operations = [
        migrations.RunPython(update_team_youtube_accounts),
        migrations.RunPython(update_sync_history_is_latest),
    ]
