# Amara, universalsubtitles.org
#
# Copyright (C) 2013 Participatory Culture Foundation
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see
# http://www.gnu.org/licenses/agpl-3.0.html.

"""externalsites.syncing.kaltura_languages -- Map language code kaltura language names.
"""

from externalsites.exceptions import SyncingError

class KalturaLanguageMap:
    # Taken from the official kaltura client
    AB = "Abkhazian"
    AA = "Afar"
    AF = "Afrikaans"
    SQ = "Albanian"
    AM = "Amharic"
    AR = "Arabic"
    HY = "Armenian"
    AS_ = "Assamese"
    AY = "Aymara"
    AZ = "Azerbaijani"
    BA = "Bashkir"
    EU = "Basque"
    BN = "Bengali (Bangla)"
    DZ = "Bhutani"
    BH = "Bihari"
    BI = "Bislama"
    BR = "Breton"
    BG = "Bulgarian"
    MY = "Burmese"
    BE = "Byelorussian (Belarusian)"
    KM = "Cambodian"
    CA = "Catalan"
    ZH = "Chinese"
    CO = "Corsican"
    HR = "Croatian"
    CS = "Czech"
    DA = "Danish"
    NL = "Dutch"
    EN = "English"
    EO = "Esperanto"
    ET = "Estonian"
    FO = "Faeroese"
    FA = "Farsi"
    FJ = "Fiji"
    FI = "Finnish"
    FR = "French"
    FY = "Frisian"
    GV = "Gaelic (Manx)"
    GD = "Gaelic (Scottish)"
    GL = "Galician"
    KA = "Georgian"
    DE = "German"
    EL = "Greek"
    KL = "Greenlandic"
    GN = "Guarani"
    GU = "Gujarati"
    HA = "Hausa"
    IW = "Hebrew"
    HE = "Hebrew"
    HI = "Hindi"
    HU = "Hungarian"
    IS = "Icelandic"
    IN = "Indonesian"
    ID = "Indonesian"
    IA = "Interlingua"
    IE = "Interlingue"
    IU = "Inuktitut"
    IK = "Inupiak"
    GA = "Irish"
    IT = "Italian"
    JA = "Japanese"
    JV = "Javanese"
    KN = "Kannada"
    KS = "Kashmiri"
    KK = "Kazakh"
    RW = "Kinyarwanda (Ruanda)"
    KY = "Kirghiz"
    RN = "Kirundi (Rundi)"
    KO = "Korean"
    KU = "Kurdish"
    LO = "Laothian"
    LA = "Latin"
    LV = "Latvian (Lettish)"
    LI = "Limburgish ( Limburger)"
    LN = "Lingala"
    LT = "Lithuanian"
    MK = "Macedonian"
    MG = "Malagasy"
    MS = "Malay"
    ML = "Malayalam"
    MT = "Maltese"
    MI = "Maori"
    MR = "Marathi"
    MO = "Moldavian"
    MN = "Mongolian"
    NA = "Nauru"
    NE = "Nepali"
    NO = "Norwegian"
    OC = "Occitan"
    OR_ = "Oriya"
    OM = "Oromo (Afan, Galla)"
    PS = "Pashto (Pushto)"
    PL = "Polish"
    PT = "Portuguese"
    PA = "Punjabi"
    QU = "Quechua"
    RM = "Rhaeto-Romance"
    RO = "Romanian"
    RU = "Russian"
    SM = "Samoan"
    SG = "Sangro"
    SA = "Sanskrit"
    SR = "Serbian"
    SH = "Serbo-Croatian"
    ST = "Sesotho"
    TN = "Setswana"
    SN = "Shona"
    SD = "Sindhi"
    SI = "Sinhalese"
    SS = "Siswati"
    SK = "Slovak"
    SL = "Slovenian"
    SO = "Somali"
    ES = "Spanish"
    SU = "Sundanese"
    SW = "Swahili (Kiswahili)"
    SV = "Swedish"
    TL = "Tagalog"
    TG = "Tajik"
    TA = "Tamil"
    TT = "Tatar"
    TE = "Telugu"
    TH = "Thai"
    BO = "Tibetan"
    TI = "Tigrinya"
    TO = "Tonga"
    TS = "Tsonga"
    TR = "Turkish"
    TK = "Turkmen"
    TW = "Twi"
    UG = "Uighur"
    UK = "Ukrainian"
    UR = "Urdu"
    UZ = "Uzbek"
    VI = "Vietnamese"
    VO = "Volapuk"
    CY = "Welsh"
    WO = "Wolof"
    XH = "Xhosa"
    YI = "Yiddish"
    JI = "Yiddish"
    YO = "Yoruba"
    ZU = "Zulu"

    @classmethod
    def get_name(cls, language_code):
        try:
            return getattr(cls, language_code.upper())
        except AttributeError:
            raise SyncingError("No kaltura language for %s" % language_code)
