# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-12 13:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0009_video_search_text'),
        ('videos', '0009_auto_20180919_0026'),
    ]

    operations = [
    ]
