# Amara, universalsubtitles.org
#
# Copyright (C) 2016 Participatory Culture Foundation
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see 
# http://www.gnu.org/licenses/agpl-3.0.html.

from importlib import import_module
import os

from django.conf import settings
from django.core.management.base import BaseCommand

class Command(BaseCommand):
    help = u'Build the amara documentaiton'
    
    def handle(self, *args, **kwargs):
        self.write_output(self.calc_output())

    def calc_output(self):
        output = []
        for module_name in settings.API_DOCS_MODULES:
            module = import_module(module_name)
            output.append(module.__doc__.strip())
        return '\n\n'.join(output)

    def write_output(self, output):
        path = os.path.join(settings.PROJECT_ROOT, 'docs',
                            'api-autogenerated.txt')
        with open(path, 'w') as f:
            f.write(output)

